### ISSUE TITLE
latest image run with error: "userName not right"

### ISSUE THREAD

**Issue by liuhuiping2013** [i4de/ithings#207]
latest image run error

``` bash
./init.db.sh  
docker-compose logs --tail 100 ithings
```

> ithings        | 2023-04-03T15:51:52.537+08:00   info   auth.(*LoginLogic).Login req=&{Username:ddsvr Password:iThings ClientID:dd.rpc/e4756ba1-088c-c289-8853-845b49d3e3ca Ip:172.19.0.8 Certificate:} caller
=auth/loginLogic.go:31  trace=13e6e546367c3a04d4e00cfc93f8c582  span=51c6ef7dc8b2d497
ithings        | 2023-04-03T15:51:52.538+08:00   info   deviceauth.(*LoginAuthLogic).LoginAuth req=username:"ddsvr" password:"iThings" clientID:"dd.rpc/e4756ba1-088c-c289-8853-845b49d3e3ca" ip:"172.19.0.8"c
aller=deviceauth/loginAuthLogic.go:103  trace=13e6e546367c3a04d4e00cfc93f8c582  span=51c6ef7dc8b2d497
ithings        | 2023-04-03T15:51:52.538+08:00   error  auth.(*LoginLogic).Login.rpc.ManageDevice req=&{ddsvr iThings dd.rpc/e4756ba1-088c-c289-8853-845b49d3e3ca 172.19.0.8 } err={"code":100006,"msg":"参数
错误","details":["userName not right"]} caller=auth/loginLogic.go:52    trace=13e6e546367c3a04d4e00cfc93f8c582  span=51c6ef7dc8b2d497
ithings        | 2023-04-03T15:51:52.538+08:00   error  【http handle err】router:/api/v1/things/device/auth/login err: {"code":100006,"msg":"参数错误","details":["userName not right"]}       caller=result/
httpResult.go:29        trace=13e6e546367c3a04d4e00cfc93f8c582  span=51c6ef7dc8b2d497
ithings        | 2023-04-03T15:51:52.538+08:00   info   [HTTP]  400  -  POST  /api/v1/things/device/auth/login - 172.19.0.7:41456 -     duration=0.7ms  caller=handler/loghandler.go:160        trace=13e6e546
367c3a04d4e00cfc93f8c582        span=51c6ef7dc8b2d497
ithings        | 2023-04-03T15:51:52.538+08:00   info   mqtt client connect attempt broker:tcp://172.19.0.7:1883        caller=clients/mqtt.go:45
ithings        | 2023-04-03T15:51:52.539+08:00   info   auth.(*LoginLogic).Login req=&{Username:ddsvr Password:iThings ClientID:dd.rpc/e4756ba1-088c-c289-8853-845b49d3e3ca Ip:172.19.0.8 Certificate:} caller
=auth/loginLogic.go:31  trace=beff4ceedfdfaa02e847c9efd898a262  span=1a3d4901d4b72dc3
ithings        | 2023-04-03T15:51:52.539+08:00   info   deviceauth.(*LoginAuthLogic).LoginAuth req=username:"ddsvr" password:"iThings" clientID:"dd.rpc/e4756ba1-088c-c289-8853-845b49d3e3ca" ip:"172.19.0.8"c
aller=deviceauth/loginAuthLogic.go:103  trace=beff4ceedfdfaa02e847c9efd898a262  span=1a3d4901d4b72dc3
ithings        | 2023-04-03T15:51:52.539+08:00   info   [HTTP]  400  -  POST  /api/v1/things/device/auth/login - 172.19.0.7:43627 -     duration=0.3ms  caller=handler/loghandler.go:160        trace=beff4cee
dfdfaa02e847c9efd898a262        span=1a3d4901d4b72dc3
ithings        | 2023-04-03T15:51:52.539+08:00   error  auth.(*LoginLogic).Login.rpc.ManageDevice req=&{ddsvr iThings dd.rpc/e4756ba1-088c-c289-8853-845b49d3e3ca 172.19.0.8 } err={"code":100006,"msg":"参数
错误","details":["userName not right"]} caller=auth/loginLogic.go:52    trace=beff4ceedfdfaa02e847c9efd898a262  span=1a3d4901d4b72dc3
ithings        | 2023-04-03T15:51:52.539+08:00   error  【http handle err】router:/api/v1/things/device/auth/login err: {"code":100006,"msg":"参数错误","details":["userName not right"]}       caller=result/
httpResult.go:29        trace=beff4ceedfdfaa02e847c9efd898a262  span=1a3d4901d4b72dc3
ithings        | 2023-04-03T15:51:56.534+08:00   info   mqtt Connect failure    caller=clients/mqtt.go:54
ithings        | 2023-04-03T15:51:56.534+08:00   error  NewDevClient errmqtt client connect failure     caller=svc/serviceContext.go:20

image version:
`
docker pull ghcr.io/i4de/ithings:sha256-daf2e7b10b71be69584c44808099437c29ce915a5cd70e773e0428daad2e055b.sig
`

**Comment by godLei6** [comment]
因为docker-compose启动顺序是不能控制的,如果出现这种情况,可以执行以下命令来重启iThings:

**Comment by godLei6** [comment]
感谢,快速解决的方法:
在deploy/conf/ithings/apisvr/etc/dm.yaml 文件中的AuthWhite.IpRange 加上172.19.0.8
然后重启iThings,执行: ` docker-compose restart  ithings`

**Comment by godLei6** [comment]
最新版本已经修复,可以拉下代码即可
